const express = require('express');
const User = require('../models/user.model');
const router = express.Router();
const jwtHelper = require('../config/jwtHelper');
const ctrlUser = require('../controller/user.controller');
const passport = require('passport');
router.post('/signup', ctrlUser.signup);
router.post('/authenticate', ctrlUser.login);
router.get('/getUser',jwtHelper.verifyJwtToken, ctrlUser.getUser);
router.get('/loggedUsers', ctrlUser.loggedIn);
module.exports = router;